export const subjects = [
  {
    id: 'os',
    name: 'Operating Systems',
    icon: '🖥️',
    topics: [
      { id: 'os-1', name: 'Process Management & Scheduling' },
      { id: 'os-2', name: 'Threads & Concurrency' },
      { id: 'os-3', name: 'Deadlocks' },
      { id: 'os-4', name: 'Memory Management & Virtual Memory' },
      { id: 'os-5', name: 'File Systems & I/O' },
      { id: 'os-6', name: 'Disk Scheduling Algorithms' },
      { id: 'os-7', name: 'Process Synchronization' },
    ],
  },
  {
    id: 'dbms',
    name: 'DBMS',
    icon: '🗄️',
    topics: [
      { id: 'dbms-1', name: 'ER Model & Relational Model' },
      { id: 'dbms-2', name: 'SQL & Relational Algebra' },
      { id: 'dbms-3', name: 'Normalization (1NF – BCNF)' },
      { id: 'dbms-4', name: 'Transactions & Concurrency Control' },
      { id: 'dbms-5', name: 'Indexing (B/B+ Trees, Hashing)' },
      { id: 'dbms-6', name: 'Recovery & Logging' },
      { id: 'dbms-7', name: 'Query Optimization' },
    ],
  },
  {
    id: 'cn',
    name: 'Computer Networks',
    icon: '🌐',
    topics: [
      { id: 'cn-1', name: 'OSI & TCP/IP Models' },
      { id: 'cn-2', name: 'Data Link Layer Protocols' },
      { id: 'cn-3', name: 'Network Layer & IP Addressing' },
      { id: 'cn-4', name: 'Routing Algorithms' },
      { id: 'cn-5', name: 'Transport Layer (TCP/UDP)' },
      { id: 'cn-6', name: 'Application Layer Protocols' },
      { id: 'cn-7', name: 'Network Security Basics' },
      { id: 'cn-8', name: 'Subnetting & CIDR' },
    ],
  },
  {
    id: 'algo',
    name: 'Algorithms',
    icon: '⚡',
    topics: [
      { id: 'algo-1', name: 'Asymptotic Analysis & Recurrences' },
      { id: 'algo-2', name: 'Divide and Conquer' },
      { id: 'algo-3', name: 'Greedy Algorithms' },
      { id: 'algo-4', name: 'Dynamic Programming' },
      { id: 'algo-5', name: 'Graph Algorithms (BFS, DFS, MST, Shortest Path)' },
      { id: 'algo-6', name: 'Sorting & Searching' },
      { id: 'algo-7', name: 'NP-Completeness' },
    ],
  },
  {
    id: 'ds',
    name: 'Data Structures',
    icon: '🏗️',
    topics: [
      { id: 'ds-1', name: 'Arrays & Linked Lists' },
      { id: 'ds-2', name: 'Stacks & Queues' },
      { id: 'ds-3', name: 'Trees (Binary, BST, AVL)' },
      { id: 'ds-4', name: 'Heaps & Priority Queues' },
      { id: 'ds-5', name: 'Hashing' },
      { id: 'ds-6', name: 'Graphs (Representation & Traversal)' },
      { id: 'ds-7', name: 'Tries & Advanced Data Structures' },
    ],
  },
  {
    id: 'toc',
    name: 'Theory of Computation',
    icon: '🔄',
    topics: [
      { id: 'toc-1', name: 'Regular Languages & Finite Automata' },
      { id: 'toc-2', name: 'Regular Expressions & Grammars' },
      { id: 'toc-3', name: 'Context-Free Languages & PDAs' },
      { id: 'toc-4', name: 'Turing Machines' },
      { id: 'toc-5', name: 'Decidability & Undecidability' },
      { id: 'toc-6', name: 'Chomsky Hierarchy' },
    ],
  },
  {
    id: 'cd',
    name: 'Compiler Design',
    icon: '🔧',
    topics: [
      { id: 'cd-1', name: 'Lexical Analysis' },
      { id: 'cd-2', name: 'Parsing (Top-Down & Bottom-Up)' },
      { id: 'cd-3', name: 'Syntax-Directed Translation' },
      { id: 'cd-4', name: 'Intermediate Code Generation' },
      { id: 'cd-5', name: 'Code Optimization' },
      { id: 'cd-6', name: 'Runtime Environments' },
    ],
  },
  {
    id: 'coa',
    name: 'Computer Organization & Architecture',
    icon: '🔩',
    topics: [
      { id: 'coa-1', name: 'Number Representation & ALU' },
      { id: 'coa-2', name: 'Processor Design & Datapath' },
      { id: 'coa-3', name: 'Pipelining & Hazards' },
      { id: 'coa-4', name: 'Memory Hierarchy & Cache' },
      { id: 'coa-5', name: 'I/O Organization' },
      { id: 'coa-6', name: 'Instruction Set Architecture' },
      { id: 'coa-7', name: 'Instruction Pipelining' },
    ],
  },
  {
    id: 'dl',
    name: 'Digital Logic',
    icon: '💡',
    topics: [
      { id: 'dl-1', name: 'Boolean Algebra & Logic Gates' },
      { id: 'dl-2', name: 'Combinational Circuits (Mux, Decoder, Adder)' },
      { id: 'dl-3', name: 'Sequential Circuits (Flip-Flops, Counters)' },
      { id: 'dl-4', name: 'Minimization (K-Maps, QM Method)' },
      { id: 'dl-5', name: 'Number Systems & Codes' },
      { id: 'dl-6', name: 'Finite State Machines' },
    ],
  },
  {
    id: 'math',
    name: 'Engineering Mathematics',
    icon: '📐',
    topics: [
      { id: 'math-1', name: 'Discrete Mathematics & Logic' },
      { id: 'math-2', name: 'Combinatorics & Graph Theory' },
      { id: 'math-3', name: 'Linear Algebra' },
      { id: 'math-4', name: 'Probability & Statistics' },
      { id: 'math-5', name: 'Calculus' },
      { id: 'math-6', name: 'Set Theory & Relations' },
      { id: 'math-7', name: 'Numerical Methods' },
    ],
  },
];
