export const subjects = [
  {
    id: 'em',
    name: 'Engineering\nMathematics',
    icon: '📐',
    topics: [
      { id: 'em-1', name: 'Discrete Mathematics: Logic & Sets' },
      { id: 'em-2', name: 'Discrete: Combinatorics & Graph Theory' },
      { id: 'em-3', name: 'Linear Algebra: Matrices & Systems' },
      { id: 'em-4', name: 'Linear Algebra: Eigenvalues & Vectors' },
      { id: 'em-5', name: 'Calculus: Limits, Continuity, Differentiability' },
      { id: 'em-6', name: 'Calculus: Maximum, Minimum, Mean Value' },
      { id: 'em-7', name: 'Calculus: Integration & Vector Calculus' },
      { id: 'em-8', name: 'Probability: Random Variables & Distributions' },
      { id: 'em-9', name: 'Probability: Statistics & Bayes Theorem' },
    ],
  },
  {
    id: 'dl',
    name: 'Digital Logic',
    icon: '💡',
    topics: [
      { id: 'dl-1', name: 'Boolean Algebra & Minimization (K-Maps)' },
      { id: 'dl-2', name: 'Combinational Circuits (Mux, Decoder, Adder)' },
      { id: 'dl-3', name: 'Sequential Circuits (Flip-Flops, Counters)' },
      { id: 'dl-4', name: 'Number Representations (Fixed & Floating Point)' },
      { id: 'dl-5', name: 'Data Representation & Computer Arithmetic' },
    ],
  },
  {
    id: 'coa',
    name: 'Computer Organization',
    icon: '🔩',
    topics: [
      { id: 'coa-1', name: 'Machine Instructions & Addressing Modes' },
      { id: 'coa-2', name: 'ALU, Data Path & Control Unit' },
      { id: 'coa-3', name: 'Instruction Pipelining & Hazards' },
      { id: 'coa-4', name: 'Memory Hierarchy: Cache & Main Memory' },
      { id: 'coa-5', name: 'Secondary Storage & I/O Interface' },
    ],
  },
  {
    id: 'pds',
    name: 'Programming & Data Structures',
    icon: '🏗️',
    topics: [
      { id: 'pds-1', name: 'Programming in C: Pointers & Memory' },
      { id: 'pds-2', name: 'Recursion' },
      { id: 'pds-3', name: 'Arrays, Stacks, Queues, Linked Lists' },
      { id: 'pds-4', name: 'Trees: Binary Search Trees, Binary Heaps' },
      { id: 'pds-5', name: 'Graph Representations & Traversals' },
    ],
  },
  {
    id: 'algo',
    name: 'Algorithms',
    icon: '⚡',
    topics: [
      { id: 'algo-1', name: 'Asymptotic Analysis & Time Complexity' },
      { id: 'algo-2', name: 'Sorting & Searching Algorithms' },
      { id: 'algo-3', name: 'Greedy Algorithms (MST, Huffman)' },
      { id: 'algo-4', name: 'Dynamic Programming (Knapsack, LCS)' },
      { id: 'algo-5', name: 'Divide & Conquer' },
      { id: 'algo-6', name: 'Graph Algorithms (BFS, DFS, Shortest Path)' },
    ],
  },
  {
    id: 'toc',
    name: 'Theory of Computation',
    icon: '🔄',
    topics: [
      { id: 'toc-1', name: 'Regular Languages & Finite Automata' },
      { id: 'toc-2', name: 'Context-Free Languages & Pushdown Automata' },
      { id: 'toc-3', name: 'Recursive Enumerable Sets & Turing Machines' },
      { id: 'toc-4', name: 'Undecidability' },
      { id: 'toc-5', name: 'Pumping Lemma & Closure Properties' },
    ],
  },
  {
    id: 'cd',
    name: 'Compiler Design',
    icon: '🔧',
    topics: [
      { id: 'cd-1', name: 'Lexical Analysis' },
      { id: 'cd-2', name: 'Parsing: Top-Down & Bottom-Up' },
      { id: 'cd-3', name: 'Syntax-Directed Translation' },
      { id: 'cd-4', name: 'Runtime Environments' },
      { id: 'cd-5', name: 'Intermediate Code Generation' },
      { id: 'cd-6', name: 'Code Optimization: Local & Data Flow' },
    ],
  },
  {
    id: 'os',
    name: 'Operating Systems',
    icon: '🖥️',
    topics: [
      { id: 'os-1', name: 'Process Management: Processes & Threads' },
      { id: 'os-2', name: 'CPU Scheduling Algorithms' },
      { id: 'os-3', name: 'Process Synchronization & Deadlocks' },
      { id: 'os-4', name: 'Memory Management' },
      { id: 'os-5', name: 'Virtual Memory (Paging, Segmentation)' },
      { id: 'os-6', name: 'File Systems' },
      { id: 'os-7', name: 'I/O Systems & Disk Scheduling' },
    ],
  },
  {
    id: 'dbms',
    name: 'Databases',
    icon: '🗄️',
    topics: [
      { id: 'dbms-1', name: 'ER Model & Relational Model' },
      { id: 'dbms-2', name: 'Relational Algebra & Tuple Calculus' },
      { id: 'dbms-3', name: 'SQL (Queries, Joins, Constraints)' },
      { id: 'dbms-4', name: 'Normalization (1NF to BCNF)' },
      { id: 'dbms-5', name: 'Transactions & Concurrency Control' },
      { id: 'dbms-6', name: 'File Organization & Indexing (B/B+ Trees)' },
    ],
  },
  {
    id: 'cn',
    name: 'Computer Networks',
    icon: '🌐',
    topics: [
      { id: 'cn-1', name: 'OSI & TCP/IP Layering Models' },
      { id: 'cn-2', name: 'Data Link Layer: Framing, Error Control' },
      { id: 'cn-3', name: 'Medium Access Control (CSMA/CD, Ethernet)' },
      { id: 'cn-4', name: 'Network Layer: Routing (Distance Vector, Link State)' },
      { id: 'cn-5', name: 'IP Addressing: IPv4, CIDR, Subnetting' },
      { id: 'cn-6', name: 'Transport Layer: TCP, UDP, Congestion Control' },
      { id: 'cn-7', name: 'Application Layer: DNS, HTTP, SMTP, FTP' },
      { id: 'cn-8', name: 'Network Security Basics' },
    ],
  },
  {
    id: 'ga',
    name: 'General Aptitude',
    icon: '🧠',
    topics: [
      { id: 'ga-1', name: 'Verbal Aptitude: Grammar & Vocabulary' },
      { id: 'ga-2', name: 'Verbal Aptitude: Reading Comprehension' },
      { id: 'ga-3', name: 'Quantitative: Numerical Computation' },
      { id: 'ga-4', name: 'Quantitative: Mensuration & Geometry' },
      { id: 'ga-5', name: 'Quantitative: Data Interpretation' },
      { id: 'ga-6', name: 'Analytical Aptitude: Logic & Patterns' },
      { id: 'ga-7', name: 'Spatial Aptitude' },
    ],
  },
];
